### ISSUE TITLE
Error when used with Unraid

### ISSUE THREAD

**Issue by sekhu-net** [athphane/clone-hero-server-docker#3]
I am using Unraid with the Docker Compose Plugin and having trouble getting the server to work. I get the following error 

> failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

I have copied the compose example and edited as needed, eg. changed the server name and the password and left everything else intact. It finishes the build but does not run. Here is the full output

> Compose can now delegate builds to bake for better performance.
 To do so, set COMPOSE_BAKE=true.
[+] Building 0.1s (1/1) FINISHED                                                                                                                     docker:default
 => [clone-hero-server internal] load build definition from Dockerfile                                                                                         0.0s
 => => transferring dockerfile: 2B                                                                                                                             0.0s
failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

**Comment by athphane** [comment]
Hi!

The example I provided in the readme is completely wrong oh god. 

The docker-compose file in the repository is what I use to build and publish the image itself. The image is available at `ghcr.io/athphane/clone-hero-server-docker:latest`

Which means you can do the following to run the server. 

```yaml
services:
  clone-hero-server:
    image: ghcr.io/athphane/clone-hero-server-docker:latest
    ports:
      - "14242:14242"
    environment:
      SERVER_NAME: "My Clone Hero Server"
      SERVER_PASSWORD: rockon
      CONNECT_IP: 0.0.0.0
      CONNECT_PORT: 14242
    container_name: clone-hero-server
    restart: unless-stopped
```
